# Generated by Django 4.2.11 on 2024-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texto')),
                ('Admiração', models.BooleanField(default=False, verbose_name='Admiração')),
                ('Diversão', models.BooleanField(default=False, verbose_name='Diversão')),
                ('Raiva', models.BooleanField(default=False, verbose_name='Raiva')),
                ('Irritação', models.BooleanField(default=False, verbose_name='Irritação')),
                ('Aprovação', models.BooleanField(default=False, verbose_name='Aprovação')),
                ('Cuidado', models.BooleanField(default=False, verbose_name='Cuidado')),
                ('Confusão', models.BooleanField(default=False, verbose_name='Confusão')),
                ('Curiosidade', models.BooleanField(default=False, verbose_name='Curiosidade')),
                ('Desejo', models.BooleanField(default=False, verbose_name='Desejo')),
                ('Desapontamento', models.BooleanField(default=False, verbose_name='Desapontamento')),
                ('Desaprovação', models.BooleanField(default=False, verbose_name='Desaprovação')),
                ('Nojo', models.BooleanField(default=False, verbose_name='Nojo')),
                ('Embaraço', models.BooleanField(default=False, verbose_name='Embaraço')),
                ('Excitação', models.BooleanField(default=False, verbose_name='Excitação')),
                ('Medo', models.BooleanField(default=False, verbose_name='Medo')),
                ('Gratidão', models.BooleanField(default=False, verbose_name='Gratidão')),
                ('Luto', models.BooleanField(default=False, verbose_name='Luto')),
                ('Alegria', models.BooleanField(default=False, verbose_name='Alegria')),
                ('Amor', models.BooleanField(default=False, verbose_name='Amor')),
                ('Nervosismo', models.BooleanField(default=False, verbose_name='Nervosismo')),
                ('Otimismo', models.BooleanField(default=False, verbose_name='Otimismo')),
                ('Orgulho', models.BooleanField(default=False, verbose_name='Orgulho')),
                ('Realização', models.BooleanField(default=False, verbose_name='Realização')),
                ('Alívio', models.BooleanField(default=False, verbose_name='Alívio')),
                ('Remorso', models.BooleanField(default=False, verbose_name='Remorso')),
                ('Tristeza', models.BooleanField(default=False, verbose_name='Tristeza')),
                ('Surpresa', models.BooleanField(default=False, verbose_name='Surpresa')),
            ],
        ),
    ]
