# Generated by Django 4.2.11 on 2024-05-30 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texto')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alegria', models.BooleanField(default=False, verbose_name='Alegria')),
                ('raiva', models.BooleanField(default=False, verbose_name='Raiva')),
                ('tristeza', models.BooleanField(default=False, verbose_name='Tristeza')),
                ('medo', models.BooleanField(default=False, verbose_name='Medo')),
                ('nojo', models.BooleanField(default=False, verbose_name='Nojo')),
                ('surpresa', models.BooleanField(default=False, verbose_name='Surpresa')),
                ('neutro', models.BooleanField(default=False, verbose_name='Neutro')),
                ('foi_dificil', models.BooleanField(default=False, verbose_name='Difícil')),
                ('facil', models.BooleanField(default=False, verbose_name='Fácil')),
                ('nenhum_nem_outro', models.BooleanField(default=False, verbose_name='Mais ou Menos')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'text')},
            },
        ),
    ]
