# Generated by Django 4.2.11 on 2024-05-01 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='Admiração',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Alegria',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Alívio',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Amor',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Aprovação',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Confusão',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Cuidado',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Curiosidade',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Desapontamento',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Desaprovação',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Desejo',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Diversão',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Embaraço',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Excitação',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Gratidão',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Irritação',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Luto',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Medo',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Nervosismo',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Nojo',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Orgulho',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Otimismo',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Raiva',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Realização',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Remorso',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Surpresa',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Tristeza',
        ),
        migrations.CreateModel(
            name='Avaliação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admiração', models.BooleanField(default=False, verbose_name='Admiração')),
                ('Diversão', models.BooleanField(default=False, verbose_name='Diversão')),
                ('Raiva', models.BooleanField(default=False, verbose_name='Raiva')),
                ('Irritação', models.BooleanField(default=False, verbose_name='Irritação')),
                ('Aprovação', models.BooleanField(default=False, verbose_name='Aprovação')),
                ('Cuidado', models.BooleanField(default=False, verbose_name='Cuidado')),
                ('Confusão', models.BooleanField(default=False, verbose_name='Confusão')),
                ('Curiosidade', models.BooleanField(default=False, verbose_name='Curiosidade')),
                ('Desejo', models.BooleanField(default=False, verbose_name='Desejo')),
                ('Desapontamento', models.BooleanField(default=False, verbose_name='Desapontamento')),
                ('Desaprovação', models.BooleanField(default=False, verbose_name='Desaprovação')),
                ('Nojo', models.BooleanField(default=False, verbose_name='Nojo')),
                ('Embaraço', models.BooleanField(default=False, verbose_name='Embaraço')),
                ('Excitação', models.BooleanField(default=False, verbose_name='Excitação')),
                ('Medo', models.BooleanField(default=False, verbose_name='Medo')),
                ('Gratidão', models.BooleanField(default=False, verbose_name='Gratidão')),
                ('Luto', models.BooleanField(default=False, verbose_name='Luto')),
                ('Alegria', models.BooleanField(default=False, verbose_name='Alegria')),
                ('Amor', models.BooleanField(default=False, verbose_name='Amor')),
                ('Nervosismo', models.BooleanField(default=False, verbose_name='Nervosismo')),
                ('Otimismo', models.BooleanField(default=False, verbose_name='Otimismo')),
                ('Orgulho', models.BooleanField(default=False, verbose_name='Orgulho')),
                ('Realização', models.BooleanField(default=False, verbose_name='Realização')),
                ('Alívio', models.BooleanField(default=False, verbose_name='Alívio')),
                ('Remorso', models.BooleanField(default=False, verbose_name='Remorso')),
                ('Tristeza', models.BooleanField(default=False, verbose_name='Tristeza')),
                ('Surpresa', models.BooleanField(default=False, verbose_name='Surpresa')),
                ('Neutro', models.BooleanField(default=False, verbose_name='Neutro')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'text')},
            },
        ),
    ]
