# Generated by Django 4.2.11 on 2024-05-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0004_rename_alegria_avaliação_alegria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliação',
            name='foi_dificil',
            field=models.BooleanField(default=False, verbose_name='Foi Difícil?'),
        ),
        migrations.AddField(
            model_name='avaliação',
            name='neutro',
            field=models.BooleanField(default=False, verbose_name='Neutro'),
        ),
    ]
